# Generated by Django 5.0.2 on 2024-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
