# Generated by Django 5.0.2 on 2024-03-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
